name: graph_rnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy<2
  - scipy
  - matplotlib
  - scikit-learn
  - pandas
  - pytorch
  - torchvision
  - networkx=3.2.1
  - pip:
    - tensorboard_logger
    - python-louvain
    - protobuf<=3.20